# Generated by Django 3.1.6 on 2021-05-20 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAppointment',
            fields=[
                ('requestAppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentType', models.CharField(choices=[('Requesting for Blood Donation', 'Requesting for Immediate Transfusion')], max_length=100)),
                ('setDate', models.DateField()),
                ('setTime', models.TimeField()),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('contactNumber', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('requestOrganizerID', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=100)),
                ('businessEmail', models.EmailField(max_length=100)),
                ('contactInfo', models.CharField(max_length=20)),
                ('attachmentsID', models.FileField(upload_to='')),
                ('attachmentsBC', models.FileField(upload_to='')),
                ('isApproved', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('requestDonorID', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('donorBloodType', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('attachmentsDonor', models.FileField(upload_to='')),
                ('isApproved', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
