# Generated by Django 3.1.6 on 2021-05-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestOrganizer',
            fields=[
                ('requestOrganizerID', models.AutoField(primary_key=True, serialize=False)),
                ('hospitalName', models.CharField(max_length=100)),
                ('hospitalAddress', models.CharField(max_length=100)),
                ('businessEmail', models.EmailField(max_length=100)),
                ('contactInfo', models.CharField(max_length=11)),
                ('isApproved', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
