# Generated by Django 3.1.10 on 2021-05-26 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodBank',
            fields=[
                ('bloodBankID', models.AutoField(primary_key=True, serialize=False)),
                ('oPlus', models.CharField(max_length=100)),
                ('oMinus', models.CharField(max_length=100)),
                ('aPlus', models.CharField(max_length=100)),
                ('aMinus', models.CharField(max_length=100)),
                ('bPlus', models.CharField(max_length=100)),
                ('bMinus', models.CharField(max_length=100)),
                ('aBPlus', models.CharField(max_length=100)),
                ('aBMinus', models.CharField(max_length=100)),
                ('hospitalName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
