# Generated by Django 3.1.10 on 2021-05-08 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestDonor',
            fields=[
                ('requestDonorID', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=200)),
                ('donorBloodType', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('isApproved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
