# Generated by Django 3.1.6 on 2021-05-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210523_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoraccount',
            name='setStatus',
            field=models.CharField(choices=[('Ready to Donate', 'Ready to Donate'), ('Has Donated', 'Has Donated'), ('Waiting Appointment', 'Waiting Appointment')], max_length=100),
        ),
    ]
