# Generated by Django 3.1.10 on 2021-05-26 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bloodbank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodbank',
            name='hospitalName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organizer'),
        ),
    ]
