# Generated by Django 3.1.6 on 2021-05-23 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210523_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donoraccount',
            name='username',
        ),
    ]
