# Generated by Django 3.1.10 on 2021-05-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_requestdonor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdonor',
            name='requestDonorID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
