# Generated by Django 3.1.10 on 2021-05-10 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210510_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='requestdonor',
            old_name='user',
            new_name='username',
        ),
    ]
