# Generated by Django 3.1.6 on 2021-05-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_donoraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setStatus', models.CharField(choices=[('Ready to Donate', 'Ready to Donate'), ('Has Donated', 'Has Donated'), ('Waiting Appointment', 'Waiting Appointment')], max_length=100)),
                ('writeReminder', models.TextField(max_length=300)),
                ('requestDonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
