# Generated by Django 3.1.6 on 2021-05-16 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210512_1109'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestOrganizer',
        ),
    ]
