# Generated by Django 3.1.6 on 2021-05-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_requestorganizer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestorganizer',
            name='contactInfo',
            field=models.CharField(max_length=20),
        ),
    ]
