# Generated by Django 3.1.6 on 2021-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_delete_donoraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAppointment',
        ),
    ]
