# Generated by Django 3.1.6 on 2021-05-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20210516_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestDonor',
        ),
    ]
