# Generated by Django 3.1.6 on 2021-05-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_requestdonor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestdonor',
            old_name='attachments',
            new_name='attachmentsDonor',
        ),
    ]
