# Generated by Django 3.1.6 on 2021-05-23 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_remove_requestappointment_requestdonorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAppointment',
        ),
    ]
