# Generated by Django 3.1.6 on 2021-05-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210519_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestDonor',
        ),
    ]
