# Generated by Django 3.1.6 on 2021-05-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_requestappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestappointment',
            name='requestDonorID',
        ),
    ]
