# Generated by Django 3.1.6 on 2021-05-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_requestappointment_requestdonorid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
