# Generated by Django 3.1.6 on 2021-05-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_donor_requestdonor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
