# Generated by Django 3.1.6 on 2021-05-23 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('DonorID', models.AutoField(primary_key=True, serialize=False)),
                ('requestAppointmentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.requestappointment')),
                ('requestDonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.requestdonor')),
            ],
        ),
    ]
