# Generated by Django 3.1.6 on 2021-05-23 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_donor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
