# Generated by Django 3.1.6 on 2021-05-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_delete_donor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestDonor',
            new_name='Donor',
        ),
    ]
