# Generated by Django 3.1.6 on 2021-05-23 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20210524_0008'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAppointment',
        ),
    ]
