# Generated by Django 3.1.6 on 2021-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_delete_requestappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAppointment',
            fields=[
                ('requestAppointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentType', models.CharField(choices=[('Requesting for Blood Donation', 'Requesting for Blood Donation'), ('Requesting for Immediate Transfusion', 'Requesting for Immediate Transfusion')], max_length=100)),
                ('setDate', models.DateField()),
                ('setTime', models.TimeField()),
                ('isApproved', models.BooleanField(default=False)),
                ('requestDonorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
