# Generated by Django 3.1.6 on 2021-05-26 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_requestappointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='attachmentsBC',
        ),
    ]
