# Generated by Django 3.1.10 on 2021-05-26 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_remove_organizer_attachmentsbc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestAppointment',
        ),
    ]
