# Generated by Django 3.1.10 on 2021-05-26 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_delete_requestappointment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='requestDonorID',
            new_name='donorID',
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointmentID', models.AutoField(primary_key=True, serialize=False)),
                ('appointmentType', models.CharField(choices=[('Requesting for Blood Donation', 'Requesting for Blood Donation'), ('Requesting for Immediate Transfusion', 'Requesting for Immediate Transfusion')], max_length=100)),
                ('setDate', models.DateField()),
                ('setTime', models.TimeField()),
                ('isApproved', models.BooleanField(default=False)),
                ('donorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.donor')),
            ],
        ),
    ]
