# Generated by Django 3.1.10 on 2021-05-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_auto_20210526_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='requestOrganizerID',
            new_name='organizerID',
        ),
    ]
