# Generated by Django 3.1.10 on 2021-05-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_auto_20210526_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizer',
            name='organizerID',
        ),
        migrations.AlterField(
            model_name='organizer',
            name='hospitalName',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
