# Generated by Django 3.1.10 on 2021-05-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_auto_20210526_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizer',
            name='hospitalName',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
