# Generated by Django 3.1.10 on 2021-05-26 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_auto_20210526_2012'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organizer',
        ),
    ]
