# Generated by Django 3.1.10 on 2021-05-26 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_delete_organizer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('hospitalName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hospitalAddress', models.CharField(max_length=100)),
                ('businessEmail', models.EmailField(max_length=100)),
                ('contactInfo', models.CharField(max_length=20)),
                ('attachmentsID', models.FileField(upload_to='')),
                ('isApproved', models.BooleanField(default=False)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
